---
root: true

plugins:
  - babel

env:
  node: true
  browser: true
  es2021: true


extends:
  - "airbnb-base"

parserOptions:
  parser: "@babel/eslint-parser"
  requireConfigFile: false
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
